name: surichatapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dartz: ^0.10.0
  get_it: ^7.2.0

  freezed_annotation: ^0.15.0
#  flutter_link_preview: ^1.5.6
  cached_network_image: ^3.1.0
  provider: ^6.0.1
  firebase_auth: ^3.1.3
  firebase_database:
  firebase_analytics:
  cloud_firestore:
  firebase_storage:
  equatable: ^2.0.3
  http: ^0.13.4
  image_picker: ^0.8.2
  package_info: ^2.0.2
  shared_preferences: ^2.0.8
  firebase_messaging: ^10.0.8
  google_sign_in: ^5.1.1
  intl: ^0.17.0
  url_launcher:
  share: ^2.0.4
  google_fonts: ^2.1.0
  firebase_remote_config: ^0.11.0+1
  firebase_dynamic_links: ^2.0.10
#  qr_code_scanner: ^0.5.2
#  qr_flutter: ^4.0.0
  rxdart: ^0.27.2
  flutter_bloc: ^7.0.0

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  # freezed: ^0.12.6
  flutter_launcher_icons: ^0.9.0
  # build_runner: ^1.10.11
  # json_annotation: ^3.1.1
  # json_serializable: ^3.5.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon-400.png"
  image_path_android: "assets/images/icon-400.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon-48.png
    - assets/images/icon-480.png
    - assets/images/icon-400.png
    - assets/images/qr.png
    - assets/images/bulb.png
    - assets/images/google_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
